services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim--hy8a1PbuEAdePaaZHYx
    volumes:
      - ./config:/config
      - /mnt/data/media/tv:/tv
      - /mnt/data/media/movies:/movies
      - /mnt/data/media/music:/music
    devices:
     - /dev/dri:/dev/dri
    restart: unless-stopped
